# Server configuration
server_hostname: midominio.es
server_dir: /var/www/html/magento
server_timezone: Europe/Madrid
server_repository: https://github.com/magento/magento2.git
server_repository_version: 2.4.8
server_email: noreply@dabad.es
server_so: ubuntu
server_distro: jammy

# PHP configuration
php_version: 8.4
php_composer_version: 2.8.0

# Database configuration
mariadb_version: 11.4
mariadb_host: localhost
mariadb_user: magento
mariadb_password: magento
mariadb_name: magento

# Opensearch configuration
opensearch_host: localhost
opensearch_port: 9200
opensearch_version: 2.19.0
opensearch_password: Magento12345!

# RabbitMQ configuration
rabbitmq_host: localhost
rabbitmq_port: 5672
rabbitmq_user: magento
rabbitmq_password: magento

# Redis configuration
redis_host: localhost
redis_port: 6379

# Magento configuration
magento_public_key: MAGENTO_PUBLIC_KEY
magento_private_key: MAGENTO_PRIVATE_KEY
magento_mode: production
magento_admin_frontname: admin
magento_admin_firstname: admin
magento_admin_lastname: admin
magento_admin_email: noreply@dabad.es
magento_admin_user: admin
magento_admin_password: Admin1234!
magento_language: es_ES
magento_currency: EUR
