- name: Check Nginx
  ansible.builtin.command: nginx -v
  register: nginx_check
  ignore_errors: yes

- name: Install Nginx
  apt:
    name: nginx
    state: latest
  when: nginx_check.rc != 0

- name: Check Nginx config file
  ansible.builtin.stat:
    path: /etc/nginx/sites-available/magento
  register: nginx_config_file

- name: Add Nginx Configuration File
  template:
    src: magento.j2
    dest: /etc/nginx/sites-available/magento
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify:
  - Reload Nginx Configuration
  when: not nginx_config_file.stat.exists

- name: Create Symbolic Link
  file:
    src: /etc/nginx/sites-available/magento
    dest: /etc/nginx/sites-enabled/magento
    owner: root
    group: root
    state: link
  notify:
  - Reload Nginx Configuration
  when: not nginx_config_file.stat.exists

- name: Start Nginx Service
  service:
    name: nginx
    state: started
    enabled: true
