- name: Check PHP status
  ansible.builtin.command: php{{php_version}} --version
  register: php_check
  no_log: true
  ignore_errors: yes

- name: Download PHP GPG key
  command: wget -O /tmp/ondrej_php.gpg https://packages.sury.org/php/apt.gpg
  args:
    warn: false
  when: php_check.rc != 0

- name: Add Ondrej PHP GPG key from file
  apt_key:
    file: /tmp/ondrej_php.gpg
    state: present
  when: php_check.rc != 0

- name: Add PHP repository to the system
  command: add-apt-repository -y ppa:ondrej/php
  args:
    creates: /etc/apt/sources.list.d/ondrej-ubuntu-php*.list
  environment:
    LC_ALL: C.UTF-8
  when: php_check.rc != 0

- name: Update apt cache
  apt:
    update_cache: yes
  when: php_check.rc != 0

- name: Install PHP {{ php_version }} and Magento PHP Dependencies
  apt:
    name: [
     "php{{ php_version }}",
     "php{{ php_version }}-fpm",
     "php{{ php_version }}-bcmath",
     "php{{ php_version }}-curl",
     "php{{ php_version }}-dom",
     "php{{ php_version }}-gd",
     "php{{ php_version }}-iconv",
     "php{{ php_version }}-intl",
     "php{{ php_version }}-mbstring",
     "php{{ php_version }}-mysql",
     "php{{ php_version }}-simplexml",
     "php{{ php_version }}-soap",
     "php{{ php_version }}-xsl",
     "php{{ php_version }}-zip"
    ]
    state: latest
  when: php_check.rc != 0
